**Importing Necessary Libraries**

In [357]:
import numpy as np
from sklearn.datasets import make_regression

**Generating Dataset**

In [358]:
X, y = make_regression(n_samples=200, n_features=2, n_targets=1)

In [359]:
X[:5]

array([[-1.42889321,  0.43830998],
       [-0.96028266,  0.32263464],
       [-1.23858342,  0.84369856],
       [-0.32608852, -0.33445159],
       [-0.12617014, -1.31847296]])

In [360]:
y[:5]

array([   4.95726576,    5.63553994,   42.36365621,  -34.53139582,
       -110.96140873])

**Train-Test Split**

In [361]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [362]:
X_train.shape

(160, 2)

In [363]:
y_train.shape

(160,)

**Linear Regression Model**

In [364]:
class mylr:
    def __init__(self):
        self.coefficient = None
        self.intercept = None

    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)
        weights = np.linalg.inv(X_train.T.dot(X_train)).dot(X_train.T).dot(y_train)
        self.intercept = weights[0]
        self.coefficient = weights[1:]

    def predict(self, X_test):
        y_pred = X_test.dot(self.coefficient) + self.intercept
        return y_pred
        

**Model Fit**

In [365]:
model = mylr()
model.fit(X_train, y_train)

**Prediction**

In [366]:
y_pred = model.predict(X_test)
y_pred

array([  81.90101998, -124.20676761,  118.92521105,   20.18584042,
        -15.37368373,  121.1880211 ,  -46.21323204,    7.09615453,
         13.59012462,   82.58787654,  158.55227247, -129.68474186,
         40.31046866,  -39.49635396,  107.48889266,   78.70217658,
        -95.11558326,   19.90923346,    3.6830835 ,  -88.08263814,
          9.71399567,  -55.64467662,  -78.13232082,   11.87911785,
         39.39917762,  114.09387309,   13.96290781,   42.36365621,
         71.29354674,   27.72854888,   65.7227981 ,   74.17753796,
         45.5060307 ,  -44.04298143,  -49.35029753,  -28.98483237,
         91.32200728,    1.22146407,   65.74083702,   12.76407239])

In [369]:
print(f'Coefficients: {model.coefficient}')
print(f'Intercept: {model.intercept}')

Coefficients: [21.70905415 82.08160324]
Intercept: 4.440892098500626e-16
