#### **Importing Necessary Libraries**

In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

#### **Generating Dataset**

In [2]:
X, y = make_regression(n_samples=200, n_features=2, n_targets=1)

In [3]:
X[:5]

array([[-1.00267051,  1.67100783],
       [-0.38199627, -0.68749395],
       [ 0.59363469, -2.11805585],
       [-1.04405782,  1.27081343],
       [ 1.18987679, -2.43198201]])

In [4]:
y[:5]

array([ 20.99413282, -76.62795733, -84.56867327,  -8.12465848,
       -53.60923811])

#### **Train-Test Split**

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
X_train.shape

(160, 2)

In [7]:
y_train.shape

(160,)

#### **GD Regressor**

In [15]:
class GDRegressor():
    def __init__(self, epoch, learning_rate, batch_size):
        self.coef = None
        self.intercept = None
        self.epoch = epoch
        self.learning_rate = learning_rate
        self.batch_size = batch_size

    def fit(self, X_train, y_train):
        self.coef = np.ones(X_train.shape[1])
        self.intercept = 0

        for i in range(self.epoch):
            np.random.shuffle(X_train)
            n_mini_batches = int(np.ceil(X_train.shape[0] / self.batch_size))

            for j in range(n_mini_batches):
                X_mini = X_train[j * self.batch_size : (j + 1) * self.batch_size, :]
                y_mini = y_train[j * self.batch_size : (j + 1) * self.batch_size]

                y_pred = np.dot(X_mini, self.coef) + self.intercept

                intercept_der = -2 * np.mean(y_mini - y_pred)
                self.intercept = self.intercept - (self.learning_rate * intercept_der)

                coef_der = -2 * np.mean(np.dot((y_mini - y_pred), X_mini))
                self.coef = self.coef - (self.learning_rate * coef_der)

    def predict(self, X_test):
        return np.dot(X_test, self.coef) + self.intercept

#### **Model Fit**

In [16]:
model = GDRegressor(epoch=10, learning_rate=0.01, batch_size=10)
model.fit(X_train, y_train)

#### **Prediction**

In [18]:
model.predict(X_test)

array([ -9.78258938, -15.10565647,  14.7203861 , -17.49939048,
         5.021559  ,  -2.07114435,   8.20119922,   7.55347194,
        -7.70856298,   2.03382539, -28.23156498,  -7.74964811,
       -24.01310027,  17.35058495,  -1.83391093, -14.99788026,
        -2.92879437,   4.49263276, -23.48080893, -25.54845165,
       -16.46866806, -13.82213719, -29.25567457, -23.58405837,
       -17.78829938, -14.18704484, -15.63851509, -33.50635063,
         0.57109329, -22.10857675, -12.96655429,   4.05542962,
       -38.24700193,  21.93088897, -10.28866032, -13.82746033,
       -22.26688841, -13.35292198,  -8.82119519,  -9.50628404])

In [20]:
print(f'Coefficients: {model.coef}')
print(f'Intercept: {model.intercept}')

Coefficients: [-8.35241573 -8.35241573]
Intercept: -9.523425314360397
